[tool.poetry]
name = "bobcat-miner"
version = "0.2.0"
authors = ["Aidan Melen <aidanmelen@protonmail.com>"]
license = "MIT"
description = "A python SDK for interacting with the bobcat miner."
readme = "README.md"
homepage = "https://github.com/aidanmelen/bobcat-miner-python"
repository = "https://github.com/aidanmelen/bobcat-miner-python"
keywords = ["helium", "bobcat", "miner"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.0"
backoff = "^1.11.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[tool.black]
line-length = 80

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"