[tool.poetry]
name = "canner-python-client"
version = "0.37.1"
description = "This package provides a client interface to query Canner a distributed SQL engine. It supports Python 3.6.x, 3.7.x, and 3.8.x."
authors = ["Eaason <v6610688@gmail.com>"]
license = "MIT"
packages = [
    { include = "canner" },
    { include = "canner/**/*.py" },
]

[tool.poetry.dependencies]
python = ">=3.6, <=3.8.7"
pillow = "^8.1.2"
pyarrow = "^3.0.0"
fastparquet = "0.4.1"
json-lines = "^0.5.0"
requests =  "^2.25.1"
aiohttp = "^3.7.4"
nest-asyncio = "^1.5.1"
dataclasses = {version = "^0.8", python = "~3.6"}
numpy = {version = ">=1.19.5", python = ">=3.6.0,<=3.8.7"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
flake8 = "^3.9.0"
mypy = "^0.812"
pytest-runner = "^5.3.0"
pytest-env = "^0.6.2"
twine = "^3.4.1"
black = {version = "^21.7b0", optional = true, python = ">=3.6.2,<=3.8.7"}
Faker = {version = "^8.11.0", python = ">=3.6.0,<=3.8.7"}


[build-system]
requires = [
    "setuptools>=30.3.0,<50",
    "wheel",
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
