"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
import typing
import PySide2
import PySide2.QtCore
import PySide2.QtGui

bytes = str


class QWindowStateChangeEvent(PySide2.QtCore.QEvent):
    """
    https://doc.qt.io/qt-5/qwindowstatechangeevent.html

    **Detailed Description**
    """

    def __init__(
        self, aOldState: PySide2.QtCore.Qt.WindowStates, isOverride: bool = ...
    ) -> None:
        ...

    def isOverride(self) -> bool:
        ...

    def oldState(self) -> PySide2.QtCore.Qt.WindowStates:
        """
        https://doc.qt.io/qt-5/qwindowstatechangeevent.html#oldState

        **Qt::WindowStates QWindowStateChangeEvent::oldState() const**

        Returns the state of the window before the change.
        """
        ...
