[tool.poetry]
name = "random_colors"
version = "0.1.0"
description = ""
authors = ["Arnthor Jonsson <arnthorj2@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^8.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
poetry2setup = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
