from aioworkers.core.base import AbstractNamedEntity as AbstractNamedEntity
from aioworkers.net.web.exceptions import HttpException as HttpException
from typing import Any, Iterable, Mapping, NamedTuple

class Route(NamedTuple):
    handler: Any
    kwargs: Any

class Application(AbstractNamedEntity):
    async def init(self) -> None: ...
    def add_route(self, method, path, handler, name: Any | None = ..., **kwargs) -> None: ...
    async def handler(self, request): ...

class Resources(Iterable):
    def __init__(self, resources: Mapping) -> None: ...
    def __iter__(self): ...
