#manage-order: 12000
version: "3.3"
services:
  cronjobshell:
    build: $ODOO_HOME/images/cronjobs
    privileged: true
    command: ['echo', 'goodbye']
    restart: 'no'
    volumes:
        - "$ODOO_HOME/images/cronjobs/bin/:/usr/local/bin/:ro"
