"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

PyPI(PySide6): https://pypi.org/project/IceSpringPySideStubs-PySide6

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
import PySide2
import typing
import PySide2.QtCore
import PySide2.QtGui
import PySide2.QtWidgets

bytes = str


class QStyleOptionFocusRect(PySide2.QtWidgets.QStyleOption):
    """
    https://doc.qt.io/qt-5/qstyleoptionfocusrect.html

    **Detailed Description**

    For performance reasons, the access to the member variables is direct (i.e.,
    using the `.` or `->` operator). This low-level feel makes the structures
    straightforward to use and emphasizes that these are simply parameters used
    by the style functions.

    For an example demonstrating how style options can be used, see the
    **Styles**  example.

    **See also** **QStyleOption** .
    """

    Type: QStyleOptionFocusRect = ...
    Version: QStyleOptionFocusRect = ...

    class StyleOptionType(object):
        Type: QStyleOptionFocusRect.StyleOptionType = ...

    class StyleOptionVersion(object):
        Version: QStyleOptionFocusRect.StyleOptionVersion = ...

    @typing.overload
    def __init__(self) -> None:
        """
        https://doc.qt.io/qt-5/qstyleoptionfocusrect.html#QStyleOptionFocusRect

        **QStyleOptionFocusRect::QStyleOptionFocusRect()**

        Constructs a QStyleOptionFocusRect, initializing the members variables
        to their default values.
        """
        ...

    @typing.overload
    def __init__(self, other: PySide2.QtWidgets.QStyleOptionFocusRect) -> None:
        """
        https://doc.qt.io/qt-5/qstyleoptionfocusrect.html#QStyleOptionFocusRect-
        1

        **QStyleOptionFocusRect::QStyleOptionFocusRect(const
        QStyleOptionFocusRect & other )**

        Constructs a copy of the **other** style option.
        """
        ...

    @typing.overload
    def __init__(self, version: int) -> None:
        """
        https://doc.qt.io/qt-5/qstyleoptionfocusrect.html#QStyleOptionFocusRect

        **QStyleOptionFocusRect::QStyleOptionFocusRect()**

        Constructs a QStyleOptionFocusRect, initializing the members variables
        to their default values.
        """
        ...
