[tool.poetry]
name = "boto3-post-conditions"
version = "0.3.0"
description = "Remove retry logic from boto3 clients by enforcing post-conditions."
readme = "README.md"
repository = "https://github.com/jeking3/boto3-post-conditions/"
keywords = ["boto3", "aws", "eventual consistency", "retry"]
authors = ["James E. King III <jking@apache.org>"]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
boto3 = "^1.20"
retry = "^0.9.2"

[tool.poetry.dev-dependencies]
bandit = "^1.7.1"
boto3-stubs = "^1.20.30"
coverage = "^6.1.2"
flake8 = "^4.0.1"
flake8-sfs = "^0.0.3"
moto = "^2.2.13"
mypy = "^0.930"
mypy-boto3-secretsmanager = "^1.20.1"
mypy-boto3-ssm = "^1.20.6"
pre-commit = "^2.15.0"
types-retry = "^0.9.5"
vcrpy = "^4.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
# https://github.com/python-poetry/poetry/issues/3456
name = "pypi-public"
url = "https://pypi.org/simple/"
default = true
