"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
import typing
import PySide2
import PySide2.QtCore
import PySide2.QtGui
import PySide2.QtWidgets

bytes = str


class QStyleHintReturn(object):
    """
    https://doc.qt.io/qt-5/qstylehintreturn.html

    **Detailed Description**

    QStyleHintReturn and its subclasses are used to pass information from a
    style back to the querying widget. This is most useful when the return value
    from **QStyle::styleHint** () does not provide enough detail; for example,
    when a mask is to be returned.
    """

    Version: QStyleHintReturn = ...
    SH_Default: QStyleHintReturn = ...
    Type: QStyleHintReturn = ...
    SH_Mask: QStyleHintReturn = ...
    SH_Variant: QStyleHintReturn = ...

    class HintReturnType(object):
        SH_Default: QStyleHintReturn.HintReturnType = ...
        SH_Mask: QStyleHintReturn.HintReturnType = ...
        SH_Variant: QStyleHintReturn.HintReturnType = ...

    class StyleOptionType(object):
        Type: QStyleHintReturn.StyleOptionType = ...

    class StyleOptionVersion(object):
        Version: QStyleHintReturn.StyleOptionVersion = ...

    def __init__(self, version: int = ..., type: int = ...) -> None:
        """
        https://doc.qt.io/qt-5/qstylehintreturn.html#QStyleHintReturn

        **QStyleHintReturn::QStyleHintReturn(int version =
        QStyleOption::Version, int type = SH_Default)**

        Constructs a QStyleHintReturn with version **version** and type
        **type**.

        The version has no special meaning for QStyleHintReturn; it can be used
        by subclasses to distinguish between different version of the same hint
        type.

        **See also** **QStyleOption::version**  and **QStyleOption::type** .
        """
        ...
