name: nr.proxy
version: 1.1.1
description: 'Provides proxy classes that allow accessing objects that are usually
  only accessible via

  function calls as objects directly.

  '
typed: true
requirements:
- python ^3.6
test-requirements:
- pytest
test-drivers:
- type: pytest
