[tool.poetry]
name = "zs-mixins"
version = "0.0.1"
description = ""
authors = ["codeif <me@codeif.com>"]

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = ">=1.3"
Werkzeug = ">=2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.16.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
black = "^21.12b0"
twine = "^3.7.1"

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
