hero_list = [
    {"name":"WOLVERINE", "world":"MARVEL COMICS"},
    {"name":"DEADPOOL","world": "MARVEL COMICS"},
    {"name":"ELEKTRA NATCHIOS", "world":"MARVEL COMICS"},
    {"name":"JOHN WICK","world": "JOHN WICK"},
    {"name":"BLADE", "world":"MARVEL COMICS"},
    {"name":"WARIO","world": "NINTENDO"},
    {"name":"FRANK CASTLE (A.K.A. THE PUNISHER)","world": "MARVEL COMICS"},
    {"name":"AGENT 47","world": "HITMAN"},
    {"name":"ELLIE","world": "THE LAST OF US"},
    {"name":"CATWOMAN","world": "DC COMICS"},
    {"name":"KRATOS","world": "GOD OF WAR"},
    {"name":"RICK SANCHEZ", "world":"RICK AND MORTY"},
    {"name":"THE HULK", "world":"MARVEL COMICS"},
    {"name":"SNAKE PLISSKEN","world": "ESCAPE FROM NEW YORK/ESCAPE FROM L.A."},
    {"name":"LESTAT DE LIONCOURT", "world":"THE VAMPIRE CHRONICLES"},
    {"name":"VENOM","world":"MARVEL COMICS"},
    {"name":"ARYA STARK","world":"GAME OF THRONES"},
    {"name":"BENDER BENDING RODRIGUEZ","world":"FUTURAMA"},
    {"name":"DUKE NUKEM","world":"DUKE NUKEM"},
    {"name":"GHOST RIDER","world":"MARVEL COMICS"},
    {"name":"RIDDICK","world":"THE CHRONICLES OF RIDDICK"},
    {"name":"BILLY BUTCHER","world":"THE BOYS"},
    {"name":"SPIDER JERUSALEM","world":"TRANSMETROPOLITAN"},
    {"name":"KING MOB","world":"THE INVISIBLES"},
    {"name":"THE SHADE","world":"DC COMICS"},
    {"name":"LIGHT YAGAMI (A.K.A. KIRA)","world":"DEATH NOTE"},
    {"name":"AL SIMMONS (A.K.A. SPAWN)","world":"IMAGE COMICS"},
    {"name":"SHADOW","world":"SONIC"},
]