[tool.poetry]
name = "gharbala"
version = "0.1.2"
description = "Remove music from videos and publish it to wordpress as posts"
authors = ["Ahmed Kamel <k.tricky@gmail.com>"]
license = "GPL"

[tool.poetry.scripts]
gharbala = "gharbala.main:main"

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
htmlmin = "^0.1.12"
requests = "^2.26.0"
Pillow = "^8.4.0"
Jinja2 = "^3.0.3"
google-cloud-translate = "^3.6.1"
sentry-sdk = "^1.5.1"
youtube_dl = "^2021.12.17"
bs4 = "^0.0.1"
beautifulsoup4 = "^4.10.0"
internetarchive = "^2.2.0"
tornado = "^6.1"
spleeter = "^2.3.0"
loguru = "^0.5.3"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
