VERSION_YEAR = 2022
VERSION_MONTH = int('01')
VERSION_DAY = int('01')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202201011016
version_date = '2022/01/01 10:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
