"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

PyPI(PySide6): https://pypi.org/project/IceSpringPySideStubs-PySide6

PyPI(PyQt5): https://pypi.org/project/IceSpringPySideStubs-PyQt5

PyPI(PyQt6): https://pypi.org/project/IceSpringPySideStubs-PyQt6

Generated by BaiJiFeiLong@gmail.com

Licence: MIT
"""
import enum
import typing
from PyQt6 import QtGui
from PyQt6 import QtCore
from PyQt6.QtWidgets import *
import enum


class QStyleOptionButton(QStyleOption):
    """
    https://doc.qt.io/qt-6/qstyleoptionbutton.html

    **Detailed Description**

    QStyleOptionButton contains all the information that **QStyle**  functions
    need to draw graphical elements like **QPushButton** , **QCheckBox** , and
    **QRadioButton** .

    For performance reasons, there are few member functions and the access to
    the member variables is direct (i.e., using the `.` or `->` operator). This
    makes the structures straightforward to use and emphasizes that these are
    simply parameters used by the style functions.

    For an example demonstrating how style options can be used, see the
    **Styles**  example.

    **See also** **QStyleOption**  and **QStyleOptionToolButton** .
    """

    class ButtonFeature(enum.Flag):
        None_: QStyleOptionButton = ...
        Flat: QStyleOptionButton = ...
        HasMenu: QStyleOptionButton = ...
        DefaultButton: QStyleOptionButton = ...
        AutoDefaultButton: QStyleOptionButton = ...
        CommandLinkButton: QStyleOptionButton = ...

    class StyleOptionVersion(enum.Enum):
        Version: QStyleOptionButton = ...

    class StyleOptionType(enum.Enum):
        Type: QStyleOptionButton = ...

    features = ...
    icon: QtGui = ...
    iconSize: QtCore = ...
    text: str = ...

    @typing.overload
    def __init__(self) -> None:
        """
        https://doc.qt.io/qt-6/qstyleoptionbutton.html#QStyleOptionButton

        **QStyleOptionButton::QStyleOptionButton()**

        Constructs a QStyleOptionButton, initializing the members variables to
        their default values.
        """
        ...

    @typing.overload
    def __init__(self, other: "QStyleOptionButton") -> None:
        """
        https://doc.qt.io/qt-6/qstyleoptionbutton.html#QStyleOptionButton-1

        **QStyleOptionButton::QStyleOptionButton(const QStyleOptionButton &
        other )**

        Constructs a copy of the **other** style option.
        """
        ...
