[tool.poetry]
name = "aliby"
version = "0.1.4"
description = ""
authors = ["Alan Munoz <alan.munoz@ed.ac.uk>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
# extraction = {git = "ssh://git@git.ecdf.ed.ac.uk/swain-lab/python-pipeline/extraction"}
# postprocessor = {git = "ssh://git@git.ecdf.ed.ac.uk/swain-lab/python-pipeline/post-processing"}
# baby = {git = "ssh://git@git.ecdf.ed.ac.uk/swain-lab/python-pipeline/baby"}
# logfile_parser = {git = "ssh://git@git.ecdf.ed.ac.uk/swain-lab/python-pipeline/logfile_parser"}
# extraction = {path="../extraction", develop=false}
# postprocessor = {path="../postprocessor", develop=false}
# baby = {path="../baby", develop=false}
# logfile_parser = {path="../logfile_parser", develop=false}
ray = {version = "1.4.0", extras = ["tune"]}
numpy = "^1.21.4"
dask = "^2021.12.0"
pathos = "^0.2.8"
tqdm = "^4.62.3"
pandas = "^1.3.5"
scikit-image = "^0.19.1"
opencv-python = "^4.5.4"
requests-toolbelt = "^0.9.1"
h5py = "2.10"
tables = "^3.6.1"
imageio = "2.8.0"
omero-py = ">=5.6.2"
zeroc-ice = "3.6.5"
tensorflow = ">=1.15,<=2.3"
aliby-parser = "*"
aliby-extraction = "*"
aliby-post = "*"
aliby-agora = "*"
aliby-baby = "*"


[tool.poetry.dev-dependencies]
black = "^21.9b0"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
