---

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: check-toml
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
- repo: https://github.com/PyCQA/doc8
  rev: 0.8.1
  hooks:
    - id: doc8
- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
    - id: isort
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
    - id: bandit
      args: [--exclude=tests]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
