[tool.poetry]
name = "isocodes"
version = "2022.01.07"
description = "This project provides lists of various ISO standards (e.g. country, language, language scripts, and currency names) in one place"
authors = ["Atem18 <contact@atemlire.io>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mkdocs = "^1.2.2"
mkdocs-material = "^8.0.0"
mkdocstrings = "^0.16.0"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
