# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['isocodes']

package_data = \
{'': ['*'],
 'isocodes': ['share/iso-codes/json/*',
              'share/locale/ab/LC_MESSAGES/*',
              'share/locale/ace/LC_MESSAGES/*',
              'share/locale/ach/LC_MESSAGES/*',
              'share/locale/af/LC_MESSAGES/*',
              'share/locale/ak/LC_MESSAGES/*',
              'share/locale/am/LC_MESSAGES/*',
              'share/locale/an/LC_MESSAGES/*',
              'share/locale/ar/LC_MESSAGES/*',
              'share/locale/as/LC_MESSAGES/*',
              'share/locale/ast/LC_MESSAGES/*',
              'share/locale/ay/LC_MESSAGES/*',
              'share/locale/az/LC_MESSAGES/*',
              'share/locale/ba/LC_MESSAGES/*',
              'share/locale/bar/LC_MESSAGES/*',
              'share/locale/be/LC_MESSAGES/*',
              'share/locale/bg/LC_MESSAGES/*',
              'share/locale/bi/LC_MESSAGES/*',
              'share/locale/bn/LC_MESSAGES/*',
              'share/locale/bn_BD/LC_MESSAGES/*',
              'share/locale/bn_IN/LC_MESSAGES/*',
              'share/locale/br/LC_MESSAGES/*',
              'share/locale/bs/LC_MESSAGES/*',
              'share/locale/byn/LC_MESSAGES/*',
              'share/locale/ca/LC_MESSAGES/*',
              'share/locale/ce/LC_MESSAGES/*',
              'share/locale/ch/LC_MESSAGES/*',
              'share/locale/chr/LC_MESSAGES/*',
              'share/locale/ckb/LC_MESSAGES/*',
              'share/locale/crh/LC_MESSAGES/*',
              'share/locale/cs/LC_MESSAGES/*',
              'share/locale/csb/LC_MESSAGES/*',
              'share/locale/cv/LC_MESSAGES/*',
              'share/locale/cy/LC_MESSAGES/*',
              'share/locale/da/LC_MESSAGES/*',
              'share/locale/de/LC_MESSAGES/*',
              'share/locale/dv/LC_MESSAGES/*',
              'share/locale/dz/LC_MESSAGES/*',
              'share/locale/ee/LC_MESSAGES/*',
              'share/locale/el/LC_MESSAGES/*',
              'share/locale/en/LC_MESSAGES/*',
              'share/locale/eo/LC_MESSAGES/*',
              'share/locale/es/LC_MESSAGES/*',
              'share/locale/et/LC_MESSAGES/*',
              'share/locale/eu/LC_MESSAGES/*',
              'share/locale/fa/LC_MESSAGES/*',
              'share/locale/ff/LC_MESSAGES/*',
              'share/locale/fi/LC_MESSAGES/*',
              'share/locale/fil/LC_MESSAGES/*',
              'share/locale/fo/LC_MESSAGES/*',
              'share/locale/fr/LC_MESSAGES/*',
              'share/locale/frp/LC_MESSAGES/*',
              'share/locale/fur/LC_MESSAGES/*',
              'share/locale/fy/LC_MESSAGES/*',
              'share/locale/ga/LC_MESSAGES/*',
              'share/locale/gez/LC_MESSAGES/*',
              'share/locale/gl/LC_MESSAGES/*',
              'share/locale/gn/LC_MESSAGES/*',
              'share/locale/gu/LC_MESSAGES/*',
              'share/locale/gv/LC_MESSAGES/*',
              'share/locale/ha/LC_MESSAGES/*',
              'share/locale/haw/LC_MESSAGES/*',
              'share/locale/he/LC_MESSAGES/*',
              'share/locale/hi/LC_MESSAGES/*',
              'share/locale/hr/LC_MESSAGES/*',
              'share/locale/ht/LC_MESSAGES/*',
              'share/locale/hu/LC_MESSAGES/*',
              'share/locale/hy/LC_MESSAGES/*',
              'share/locale/ia/LC_MESSAGES/*',
              'share/locale/id/LC_MESSAGES/*',
              'share/locale/io/LC_MESSAGES/*',
              'share/locale/is/LC_MESSAGES/*',
              'share/locale/it/LC_MESSAGES/*',
              'share/locale/iu/LC_MESSAGES/*',
              'share/locale/ja/LC_MESSAGES/*',
              'share/locale/jam/LC_MESSAGES/*',
              'share/locale/ka/LC_MESSAGES/*',
              'share/locale/kab/LC_MESSAGES/*',
              'share/locale/ki/LC_MESSAGES/*',
              'share/locale/kk/LC_MESSAGES/*',
              'share/locale/kl/LC_MESSAGES/*',
              'share/locale/km/LC_MESSAGES/*',
              'share/locale/kmr/LC_MESSAGES/*',
              'share/locale/kn/LC_MESSAGES/*',
              'share/locale/ko/LC_MESSAGES/*',
              'share/locale/kok/LC_MESSAGES/*',
              'share/locale/kv/LC_MESSAGES/*',
              'share/locale/kw/LC_MESSAGES/*',
              'share/locale/ky/LC_MESSAGES/*',
              'share/locale/lo/LC_MESSAGES/*',
              'share/locale/lt/LC_MESSAGES/*',
              'share/locale/lv/LC_MESSAGES/*',
              'share/locale/mai/LC_MESSAGES/*',
              'share/locale/mhr/LC_MESSAGES/*',
              'share/locale/mi/LC_MESSAGES/*',
              'share/locale/mk/LC_MESSAGES/*',
              'share/locale/ml/LC_MESSAGES/*',
              'share/locale/mn/LC_MESSAGES/*',
              'share/locale/mo/LC_MESSAGES/*',
              'share/locale/mr/LC_MESSAGES/*',
              'share/locale/ms/LC_MESSAGES/*',
              'share/locale/mt/LC_MESSAGES/*',
              'share/locale/my/LC_MESSAGES/*',
              'share/locale/na/LC_MESSAGES/*',
              'share/locale/nah/LC_MESSAGES/*',
              'share/locale/nb/LC_MESSAGES/*',
              'share/locale/nb_NO/LC_MESSAGES/*',
              'share/locale/ne/LC_MESSAGES/*',
              'share/locale/nl/LC_MESSAGES/*',
              'share/locale/nn/LC_MESSAGES/*',
              'share/locale/nso/LC_MESSAGES/*',
              'share/locale/nv/LC_MESSAGES/*',
              'share/locale/oc/LC_MESSAGES/*',
              'share/locale/or/LC_MESSAGES/*',
              'share/locale/pa/LC_MESSAGES/*',
              'share/locale/pap/LC_MESSAGES/*',
              'share/locale/pi/LC_MESSAGES/*',
              'share/locale/pl/LC_MESSAGES/*',
              'share/locale/ps/LC_MESSAGES/*',
              'share/locale/pt/LC_MESSAGES/*',
              'share/locale/pt_BR/LC_MESSAGES/*',
              'share/locale/ro/LC_MESSAGES/*',
              'share/locale/ru/LC_MESSAGES/*',
              'share/locale/rw/LC_MESSAGES/*',
              'share/locale/sc/LC_MESSAGES/*',
              'share/locale/sd/LC_MESSAGES/*',
              'share/locale/si/LC_MESSAGES/*',
              'share/locale/sk/LC_MESSAGES/*',
              'share/locale/sl/LC_MESSAGES/*',
              'share/locale/so/LC_MESSAGES/*',
              'share/locale/son/LC_MESSAGES/*',
              'share/locale/sq/LC_MESSAGES/*',
              'share/locale/sr/LC_MESSAGES/*',
              'share/locale/sr@latin/LC_MESSAGES/*',
              'share/locale/sv/LC_MESSAGES/*',
              'share/locale/sw/LC_MESSAGES/*',
              'share/locale/ta/LC_MESSAGES/*',
              'share/locale/te/LC_MESSAGES/*',
              'share/locale/tg/LC_MESSAGES/*',
              'share/locale/th/LC_MESSAGES/*',
              'share/locale/ti/LC_MESSAGES/*',
              'share/locale/tig/LC_MESSAGES/*',
              'share/locale/tk/LC_MESSAGES/*',
              'share/locale/tl/LC_MESSAGES/*',
              'share/locale/tr/LC_MESSAGES/*',
              'share/locale/tt/LC_MESSAGES/*',
              'share/locale/tt@iqtelif/LC_MESSAGES/*',
              'share/locale/tzm/LC_MESSAGES/*',
              'share/locale/ug/LC_MESSAGES/*',
              'share/locale/uk/LC_MESSAGES/*',
              'share/locale/ur/LC_MESSAGES/*',
              'share/locale/uz/LC_MESSAGES/*',
              'share/locale/ve/LC_MESSAGES/*',
              'share/locale/vi/LC_MESSAGES/*',
              'share/locale/wa/LC_MESSAGES/*',
              'share/locale/wal/LC_MESSAGES/*',
              'share/locale/wo/LC_MESSAGES/*',
              'share/locale/xh/LC_MESSAGES/*',
              'share/locale/yo/LC_MESSAGES/*',
              'share/locale/zh_CN/LC_MESSAGES/*',
              'share/locale/zh_HK/LC_MESSAGES/*',
              'share/locale/zh_Hans/LC_MESSAGES/*',
              'share/locale/zh_Hant/LC_MESSAGES/*',
              'share/locale/zh_TW/LC_MESSAGES/*',
              'share/locale/zu/LC_MESSAGES/*',
              'share/pkgconfig/*',
              'share/xml/iso-codes/*']}

setup_kwargs = {
    'name': 'isocodes',
    'version': '2022.1.7',
    'description': 'This project provides lists of various ISO standards (e.g. country, language, language scripts, and currency names) in one place',
    'long_description': None,
    'author': 'Atem18',
    'author_email': 'contact@atemlire.io',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)
