VERSION_YEAR = 2022
VERSION_MONTH = int('01')
VERSION_DAY = int('01')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202201010834
version_date = '2022/01/01 08:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
