include:
  - project: computing/gitlab-ci-templates
    file:
      - debian.yml
      - python.yml
      - rhel.yml

stages:
  - dist
  - source
  - build
  - test
  - lint

# -- macros

.el7:
  image: igwn/base:el7-testing
  variables:
    EPEL: "true"

.el8:
  image: igwn/base:el8-testing
  variables:
    EPEL: "true"

.stretch:
  image: igwn/base:stretch-proposed

.buster:
  image: igwn/base:buster

.bullseye:
  image: igwn/base:bullseye

# -- dist -------------------
#
# This job makes the gwdatafind-X.Y.Z.tar.gz
# distribution and uploads it as a job
# artifact
#

tarball:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/python/#.python:build
    - .python:build
  image: python:3
  stage: dist

# -- source packages --------
#
# These jobs make src RPMs
#

.source:
  stage: source
  needs:
    - tarball

.srpm:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/rhel/#.rhel:srpm
    - .rhel:srpm
    - .source

srpm:el7:
  extends:
    - .srpm
    - .el7

srpm:el8:
  extends:
    - .srpm
    - .el8

.dsc:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/debian/#.debian:dsc
    - .debian:dsc
    - .source

dsc:stretch:
  extends:
    - .dsc
    - .stretch

dsc:buster:
  extends:
    - .dsc
    - .buster

dsc:bullseye:
  extends:
    - .dsc
    - .bullseye

# -- binary packages --------
#
# These jobs generate binary RPMs
# from the src RPMs
#

.binary:
  stage: build

.rpm:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/rhel/#.rhel:rpm
    - .rhel:rpm
    - .binary

rpm:el7:
  extends:
    - .rpm
    - .el7
  needs:
    - srpm:el7

rpm:el8:
  extends:
    - .rpm
    - .el8
  needs:
    - srpm:el8

.deb:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/debian/#.debian:deb
    - .debian:deb
    - .binary

deb:stretch:
  extends:
    - .deb
    - .stretch
  needs:
    - dsc:stretch

deb:buster:
  extends:
    - .deb
    - .buster
  needs:
    - dsc:buster

deb:bullseye:
  extends:
    - .deb
    - .bullseye
  needs:
    - dsc:bullseye

# -- test -------------------
#
# These jobs run the tests on
# all supported platforms
#

# -- test with pip

.test:
  extends:
    # because we use `apt` to install swig:
    # https://computing.docs.ligo.org/gitlab-ci-templates/debian/#.debian:base
    - .debian:base
    # https://computing.docs.ligo.org/gitlab-ci-templates/python/#.python:pytest
    - .python:pytest
  stage: test
  needs:
    - tarball
  variables:
    # don't need the git repo
    GIT_STRATEGY: none
    # configure pytest
    PYTEST_OPTIONS: "-ra -v --pyargs ecp_cookie_init.tests"
    # use python3
    PYTHON: "python3"
  before_script:
    # install swig upfront so that m2crypto builds
    - !reference [".debian:base", before_script]
    - apt-get -y install swig
    # resolve wildcard in tarball so we can specify an extra
    - TARBALL=$(echo ecp-cookie-init-*.tar.gz)
    - INSTALL_TARGET="${TARBALL}[test]"
    # configure from template
    - !reference [".python:pytest", before_script]
  script:
    # run pytest
    - !reference [".python:pytest", script]
    # run other stuff
    - python3 -m coverage run
          --append
          --source=ecp_cookie_init
          --module
          ecp_cookie_init --help

test:python3.5:
  extends:
    - .test
  image: python:3.5

test:python3.6:
  extends:
    - .test
  image: python:3.6

test:python3.7:
  extends:
    - .test
  image: python:3.7

test:python3.8:
  extends:
    - .test
  image: python:3.8

test:python3.9:
  extends:
    - .test
  image: python:3.9

# -- test RHEL

.test:el:
  extends:
    - .test
  before_script:
    # set up yum caching
    - !reference [".rhel:base", before_script]
    # configure EPEL
    - yum -y -q install epel-release && yum -y -q install epel-rpm-macros
    # install testing dependencies
    - PY3=$(rpm --eval '%{?python3_pkgversion:%{python3_pkgversion}}%{!?python3_pkgversion:3}')
    - yum -y -q install
          python${PY3}-coverage
          python${PY3}-pytest
          python${PY3}-pytest-cov
    # install our package(s)
    - yum -y install *.rpm

test:el7:
  extends:
    - .test:el
    - .el7
  needs:
    - rpm:el7

test:el8:
  extends:
    - .test:el
    - .el8
  needs:
    - rpm:el8

# -- test Debian

.test:debian:
  extends:
    - .test
    - .debian:base
  before_script:
    # set up apt
    - !reference [".debian:base", before_script]
    - apt-get -y -q -q install dpkg
    # install testing dependencies
    - apt-get -y -q install
          python3-coverage
          python3-pytest
          python3-pytest-cov
    # install our package(s)
    - dpkg --install *.deb || { apt-get -q -y -f install; dpkg -i *.deb; }

test:stretch:
  extends:
    - .test:debian
    - .stretch
  needs:
    - deb:stretch

test:buster:
  extends:
    - .test:debian
    - .buster
  needs:
    - deb:buster

test:bullseye:
  extends:
    - .test:debian
    - .bullseye
  needs:
    - deb:bullseye

# -- lint -------------------
#
# These jobs check the code
# for quality issues
#

.lint:
  stage: lint

flake8:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/python/#.python:flake8
    - .python:flake8
    - .lint
  needs: []

.rpmlint:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/rhel/#.rhel:lint
    - .rhel:lint
    - .lint
  variables:
    GIT_STRATEGY: fetch
    RPMLINT_OPTIONS: '--info --file .rpmlintrc'

rpmlint:el7:
  extends:
    - .rpmlint
    - .el7
  needs:
    - rpm:el7

rpmlint:el8:
  extends:
    - .rpmlint
    - .el8
  needs:
    - rpm:el8

.lintian:
  extends:
    # https://computing.docs.ligo.org/gitlab-ci-templates/debian/#.debian:lint
    - .debian:lint
    - .lint
  variables:
    LINTIAN_OPTIONS: "--color always --suppress-tags new-package-should-close-itp-bug --fail-on-warnings --allow-root --pedantic"

lintian:stretch:
  extends:
    - .lintian
    - .stretch
  needs:
    - deb:stretch

lintian:buster:
  extends:
    - .lintian
    - .buster
  needs:
    - deb:buster

lintian:bullseye:
  extends:
    - .lintian
    - .bullseye
  needs:
    - deb:bullseye
  variables:
    LINTIAN_OPTIONS: "--color always --suppress-tags new-package-should-close-itp-bug,groff-message --fail-on warning --allow-root --pedantic"
