[tool.poetry]
name = "mandown"
version = "0.1.0"
description = "Command line application and library to download manga from various sources"
authors = ["Daniel Chen <danielchen04@hotmail.ca>"]
license = "AGPLv3"

[tool.poetry.scripts]
mandown = "mandown:cli"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"
feedparser = "^6.0.8"
beautifulsoup4 = "^4.10.0"
requests = "^2.27.0"

[tool.poetry.dev-dependencies]
types-requests = "^2.26.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
