name: Test with different Python versions
on: [push, pull_request]
jobs:
  python:
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy-3.6"
          - "pypy-3.7"
          - "pypy-3.8"
    runs-on: ubuntu-latest
    steps:
      - name: Install PortAudio
        run: |
          sudo apt-get install --no-install-recommends libportaudio2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Double-check Python version
        run: |
          python --version
      - name: Clone Git repository
        uses: actions/checkout@v2
        with:
          path: git-repo
      - name: Install Python package
        working-directory: git-repo
        run: |
          python -m pip install .
      - name: Run tests
        run: |
          python -m sounddevice
          python -c "import sounddevice as sd; print(sd._libname)"
          python -c "import sounddevice as sd; print(sd.get_portaudio_version())"
