[tool.poetry]
name = "yubrary"
version = "1.0.0"
description = "yuuta_library"
authors = ["YAMASHITA Yuta <proyuuta0618188188@gmail.com>"]
maintainers = ["YAMASHITA Yuta <proyuuta0618188188@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/funnelyuuta/yubrary"
documentation = "https://github.com/funnelyuuta/yubrary"
include = ["LICENSE"]


[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
