[tool.poetry]
name = "jommerce"
version = "1.1.0"
description = "Jommerce"
license = "GPL-3.0-or-later"
authors = ["githashem <PersonalHashem@gmail.com>"]
readme = "README.md"
keywords = ["jommerce"]

homepage = "https://github.com/jommerce/jommerce"
repository = "https://github.com/jommerce/jommerce"
documentation = "https://jommerce.readthedocs.io/"

include = [
    "README.md",
    "LICENSE",
    "CHANGELOG.md",
    "jommerce/templates/*",
    "jommerce/static/*",
    "jommerce/project_template/*",
]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.0",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
     "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "4"
psycopg2 = { version = "^2.5.4", optional = true }

[tool.poetry.extras]
PostgreSQL = ["psycopg2"]

[tool.poetry.dev-dependencies]
black = "^21.11b1"
ipython = "^7.30.1"
sphinx = "^4.2.0"
sphinx_rtd_theme = "^1.0.0"
coverage = "^6.2"
django-debug-toolbar = "^3.2.3"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/jommerce/jommerce/issues"

[tool.poetry.scripts]
jommerce = "jommerce.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["."]
omit = ["manage.py"]

[tool.coverage.report]
skip_covered = true
