[tool.poetry]
name = "feature-store-bundle"
version = "1.4.0.dev2"
description = "Feature Store for the Daipe AI Platform"
readme = "README.md"
repository = "https://github.com/daipe-ai/feature-store-bundle"

license = "Proprietary"

authors = [
    "Datasentics <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "featurestorebundle", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
daipe-core = "^1.2"
pyfony-bundles = "0.4.*"
databricks-bundle = "^1.3.1"

[tool.poetry.dev-dependencies]
pyspark = {url = "https://daipe-packages.s3.eu-central-1.amazonaws.com/pyspark-3.2.0-py2.py3-none-any.whl"}
delta-spark = {url = "https://daipe-packages.s3.eu-central-1.amazonaws.com/delta_spark-1.1.0-py3-none-any.whl"}
ipython = "^7.30.1"
pytest = "^5.2"
pyre-check-nightly = { version = "^0.0.101638533492", markers = "sys_platform == 'linux'"}
pylint = "^2.12.2"
flake8 = "^3.9.0"
black = "^20.8b1"
flake8-fixme = "^1.1.1"
pep8-naming = "^0.11.1"
poethepoet = "^0.10.0"
pyfony-core = "0.8.*"

[tool.poetry.plugins."pyfony.bundle"]
create = "featurestorebundle.FeatureStoreBundle:FeatureStoreBundle"

[pyfony.bootstrap]
container_init = "pyfonycore.container.container_init:init_with_current_bundle"
root_module_name = "featurestorebundle"

[tool.black]
line-length = 140

[tool.poe.tasks]
black = "black src"
black-check = "black --check src"
flake8 = "flake8 --ignore=E501,W503 src"
pylint = "pylint --rcfile=.pylintrc --module-rgx=.+ src"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
