[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pdf2htmldir"
authors = [{name = "nhannht", email = "nhanclassroom@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
[project.script]
pdf2htmldir = "pdf2htmldir::main"