[tool.poetry]
name = "cleantoots"
version = "0.7.0"
description = "Cleanup your toot history."
authors = ["Gabriel Augendre <gabriel@augendre.info>"]
readme = "README.md"
homepage = "https://git.augendre.info/gaugendre/cleantoots"
repository = "https://git.augendre.info/gaugendre/cleantoots"
keywords = ["mastodon", "toot"]
classifiers = [
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Communications :: Chat",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = ">=3.8,<4"
"Mastodon.py" = ">=1.5.0"
click = ">=7.0"
pendulum = ">=2.0.5"
html2text = ">=2019.9.26"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
invoke = "^1.6.0"
pre-commit = "^2.16.0"
tox = "^3.24.4"

[tool.poetry.scripts]
cleantoots = 'cleantoots.main:cli'

[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py38, py39, py310

[testenv]
whitelist_externals = poetry
commands =
    poetry install --remove-untracked
    poetry run inv test
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
