[tool.poetry]
name = "aliby-agora"
version = "0.1.6"
description = "A gathering of shared utilities for the Swain Lab image processing pipeline."
authors = ["Alán Muñoz <amuoz@ed.ac.uk>", "Diane Adjavon <diane.adjavon@ed.ac.uk>"]
license = "GPL-3.0-or-later"
packages = [
    { include = "agora" },
]

[tool.poetry.dependencies]
python = "^3.7.1,<3.11"
numpy = "^1.21.4"
tqdm = "^4.62.3"
PyYAML = "^6.0"
omero-py = ">=5.6.2"
zeroc-ice = "3.6.5"
aliby-parser = "*"

[tool.poetry.dev-dependencies]
data-science-types = "^0.2.23"
black = "^21.12b0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"
nox = "^2021.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
