[tool.poetry]
name = "lwc_common"
version = "0.1.1"
description = ""
authors = ["AminuIsrael <israel.aminu@data2bots.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
