"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

PyPI(PySide6): https://pypi.org/project/IceSpringPySideStubs-PySide6

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
import PySide2
import typing
import PySide2.QtCore

bytes = str


class QCborParserError(object):
    """
    https://doc.qt.io/qt-5/qcborparsererror.html

    **Detailed Description**

    This class is used by **QCborValue::fromCbor** (const QByteArray &ba,
    QCborParserError *error) to report a parser error and the byte offset where
    the error was detected.

    **See also** **QCborValue**  and **QCborError** .
    """

    @typing.overload
    def __init__(self) -> None:
        ...

    @typing.overload
    def __init__(self, QCborParserError: PySide2.QtCore.QCborParserError) -> None:
        ...

    @staticmethod
    def __copy__() -> None:
        ...

    def errorString(self) -> str:
        """
        https://doc.qt.io/qt-5/qcborparsererror.html#errorString

        **QString QCborParserError::errorString() const**

        Returns a string representation of the error code. This string is not
        translated.

        **See also** **QCborError::toString** () and **QCborValue::fromCbor**
        ().
        """
        ...
