[tool.poetry]
name = "hammuon"
version = "0.1.0"
description = "Basic and important data structures algorithm"
readme = "README.md"
authors = ["mcvarer <ktuce.mcanv@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
