"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
import typing
import PySide2
import PySide2.QtCore

bytes = str


class QXmlStreamEntityResolver(object):
    """
    https://doc.qt.io/qt-5/qxmlstreamentityresolver.html

    **Detailed Description**
    """

    def __init__(self) -> None:
        ...

    def resolveEntity(self, publicId: str, systemId: str) -> str:
        ...

    def resolveUndeclaredEntity(self, name: str) -> str:
        """
        https://doc.qt.io/qt-5/qxmlstreamentityresolver.html#resolveUndeclaredEn
        tity

        **[virtual] QString
        QXmlStreamEntityResolver::resolveUndeclaredEntity(const QString & name
        )**

        Resolves the undeclared entity **name** and returns its replacement
        text. If the entity is also unknown to the entity resolver, it returns
        an empty string.

        The default implementation always returns an empty string.
        """
        ...
