ProjectTests:
  General:
    - https://github.com/KritantaDev/Chapters
    - https://github.com/KritantaDev/Docky
    - https://github.com/KritantaDev/Shakelight
    - https://github.com/KritantaDev/Gravitation
  Globbing:
    - https://github.com/KritantaDev/Signe
  Legacy:
    - https://github.com/KritantaDev/StatusViz
  Theos:
    - https://github.com/KritantaDev/StopCrashingPls
    - https://github.com/KritantaDev/libCozy
BaselineData:
  cpu_bench: 1.3837896153333336
  ProjectScores:
    https://github.com/KritantaDev/Chapters: 0.7295811089999997
    https://github.com/KritantaDev/Docky: 1.3256995099999997
    https://github.com/KritantaDev/Shakelight: 0.7603968410000022
    https://github.com/KritantaDev/StatusViz: 1.176904830999998
    https://github.com/KritantaDev/StopCrashingPls: 0.631509568000002
    https://github.com/KritantaDev/libCozy: 0.7155977580000004
