[tool.poetry]
name = "OCR"
version = "0.1.0"
description = ""
authors = ["Gal Ben Haim"]

[tool.poetry.dependencies]
python = "3.9.1"
pytesseract = "0.3.8"
opencv-python = "4.5.4.60"
pdf2image = "1.16.0"

[build-system]
requires = [
    "poetry>=1.0.5",
    "setuptools >= 40.9.0",
    "wheel",
]

build-backend = "setuptools.build_meta"
