[build-system]
requires = [
    'setuptools >= 44',
    'wheel >= 0.30',
    'setuptools_scm[toml]>=3.4',
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
profile = 'black'

[tool.mypy]
python_version = 3.9
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

[tool.setuptools_scm]
write_to = 'src/circpandas/version.py'
write_to_template = """
\"\"\" Version information \"\"\"
__version__ = "{version}"
"""
