"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

PyPI(PySide6): https://pypi.org/project/IceSpringPySideStubs-PySide6

PyPI(PyQt5): https://pypi.org/project/IceSpringPySideStubs-PyQt5

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
import typing
from PyQt5.QtWidgets import *


class QStyleOptionRubberBand(QStyleOption):
    """
    https://doc.qt.io/qt-5/qstyleoptionrubberband.html

    **Detailed Description**

    QStyleOptionRubberBand contains all the information that **QStyle**
    functions need to draw **QRubberBand** .

    For performance reasons, the access to the member variables is direct (i.e.,
    using the `.` or `->` operator). This low-level feel makes the structures
    straightforward to use and emphasizes that these are simply parameters used
    by the style functions.

    For an example demonstrating how style options can be used, see the
    **Styles**  example.

    **See also** **QStyleOption**  and **QRubberBand** .
    """

    class StyleOptionVersion(int):
        Version: QStyleOptionRubberBand = ...

    class StyleOptionType(int):
        Type: QStyleOptionRubberBand = ...

    opaque: bool = ...
    shape: QRubberBand = ...

    @typing.overload
    def __init__(self) -> None:
        """
        https://doc.qt.io/qt-5/qstyleoptionrubberband.html#QStyleOptionRubberBan
        d

        **QStyleOptionRubberBand::QStyleOptionRubberBand()**

        Creates a QStyleOptionRubberBand, initializing the members variables to
        their default values.
        """
        ...

    @typing.overload
    def __init__(self, other: "QStyleOptionRubberBand") -> None:
        """
        https://doc.qt.io/qt-5/qstyleoptionrubberband.html#QStyleOptionRubberBan
        d-1

        **QStyleOptionRubberBand::QStyleOptionRubberBand(const
        QStyleOptionRubberBand & other )**

        Constructs a copy of the **other** style option.
        """
        ...
