"""
PySide2 stub files generated by **IceSpringPySideStubs**

Home page: https://github.com/baijifeilong/IceSpringPySideStubs

Generated by BaiJiFeiLong@gmail.com

Licence: GPL-3
"""
import typing
import PySide2
import PySide2.QtCore
import PySide2.QtGui

bytes = str


class QDrag(PySide2.QtCore.QObject):
    """
    https://doc.qt.io/qt-5/qdrag.html

    **Detailed Description**

    Drag and drop is an intuitive way for users to copy or move data around in an application, and is used in many desktop environments as a mechanism for copying data between applications. Drag and drop support in Qt is centered around the QDrag class that handles most of the details of a drag and drop operation.

    The data to be transferred by the drag and drop operation is contained in a **QMimeData**  object. This is specified with the **setMimeData** () function in the following way:

    **QDrag**  *drag = new **QDrag** (this);
                **QMimeData**  *mimeData = new **QMimeData** ;

                mimeData->setText(commentEdit->toPlainText());
                drag->setMimeData(mimeData);

    Note that **setMimeData** () assigns ownership of the **QMimeData**  object to the QDrag object. The QDrag must be constructed on the heap with a parent **QObject**  to ensure that Qt can clean up after the drag and drop operation has been completed.

    A pixmap can be used to represent the data while the drag is in progress, and will move with the cursor to the drop target. This pixmap typically shows an icon that represents the MIME type of the data being transferred, but any pixmap can be set with **setPixmap** (). The cursor's hot spot can be given a position relative to the top-left corner of the pixmap with the **setHotSpot** () function. The following code positions the pixmap so that the cursor's hot spot points to the center of its bottom edge:

    drag->setHotSpot(**QPoint** (drag->pixmap().width()/2,
                                    drag->pixmap().height()));

    **Note:** On X11, the pixmap may not be able to keep up with the mouse movements if the hot spot causes the pixmap to be displayed directly under the cursor.

    The source and target widgets can be found with **source** () and **target** (). These functions are often used to determine whether drag and drop operations started and finished at the same widget, so that special behavior can be implemented.

    QDrag only deals with the drag and drop operation itself. It is up to the developer to decide when a drag operation begins, and how a QDrag object should be constructed and used. For a given widget, it is often necessary to reimplement **mousePressEvent()**  to determine whether the user has pressed a mouse button, and reimplement **mouseMoveEvent()**  to check whether a QDrag is required.

    **See also** **Drag and Drop** , **QClipboard** , **QMimeData** , **QMacPasteboardMime** , **Draggable Icons Example** , **Draggable Text Example** , **Drop Site Example** , and **Fridge Magnets Example** .
    """

    def __init__(self, dragSource: PySide2.QtCore.QObject) -> None:
        """
        https://doc.qt.io/qt-5/qdrag.html#QDrag

        **QDrag::QDrag(QObject * dragSource )**

        Constructs a new drag object for the widget specified by **dragSource**.
        """
        ...

    @staticmethod
    def cancel() -> None:
        """
        https://doc.qt.io/qt-5/qdrag.html#cancel

        **[static] void QDrag::cancel()**

        Cancels a drag operation initiated by Qt.

        **Note:** This is currently implemented on Windows and X11.

        This function was introduced in Qt 5.7.

        **See also** **exec** ().
        """
        ...

    def defaultAction(self) -> PySide2.QtCore.Qt.DropAction:
        """
        https://doc.qt.io/qt-5/qdrag.html#defaultAction

        **Qt::DropAction QDrag::defaultAction() const**

        Returns the default proposed drop action for this drag operation.

        **See also** **exec** () and **supportedActions** ().
        """
        ...

    def dragCursor(self, action: PySide2.QtCore.Qt.DropAction) -> PySide2.QtGui.QPixmap:
        """
        https://doc.qt.io/qt-5/qdrag.html#dragCursor

        **QPixmap QDrag::dragCursor(Qt::DropAction action ) const**

        Returns the drag cursor for the **action**.

        This function was introduced in Qt 5.0.

        **See also** **setDragCursor** ().
        """
        ...

    @typing.overload
    def exec_(
        self,
        supportedActions: PySide2.QtCore.Qt.DropActions,
        defaultAction: PySide2.QtCore.Qt.DropAction,
    ) -> PySide2.QtCore.Qt.DropAction:
        ...

    @typing.overload
    def exec_(
        self, supportedActions: PySide2.QtCore.Qt.DropActions = ...
    ) -> PySide2.QtCore.Qt.DropAction:
        ...

    def hotSpot(self) -> PySide2.QtCore.QPoint:
        """
        https://doc.qt.io/qt-5/qdrag.html#hotSpot

        **QPoint QDrag::hotSpot() const**

        Returns the position of the hot spot relative to the top-left corner of the cursor.

        **See also** **setHotSpot** ().
        """
        ...

    def mimeData(self) -> PySide2.QtCore.QMimeData:
        """
        https://doc.qt.io/qt-5/qdrag.html#mimeData

        **QMimeData *QDrag::mimeData() const**

        Returns the MIME data that is encapsulated by the drag object.

        **See also** **setMimeData** ().
        """
        ...

    def pixmap(self) -> PySide2.QtGui.QPixmap:
        """
        https://doc.qt.io/qt-5/qdrag.html#pixmap

        **QPixmap QDrag::pixmap() const**

        Returns the pixmap used to represent the data in a drag and drop operation.

        **See also** **setPixmap** ().
        """
        ...

    def setDragCursor(
        self, cursor: PySide2.QtGui.QPixmap, action: PySide2.QtCore.Qt.DropAction
    ) -> None:
        """
        https://doc.qt.io/qt-5/qdrag.html#setDragCursor

        **void QDrag::setDragCursor(const QPixmap & cursor , Qt::DropAction action )**

        Sets the drag **cursor** for the **action**. This allows you to override the default native cursors. To revert to using the native cursor for **action** pass in a null **QPixmap**  as **cursor**.

        Note: setting the drag cursor for IgnoreAction may not work on all platforms. X11 and macOS has been tested to work. Windows does not support it.

        **See also** **dragCursor** ().
        """
        ...

    def setHotSpot(self, hotspot: PySide2.QtCore.QPoint) -> None:
        """
        https://doc.qt.io/qt-5/qdrag.html#setHotSpot

        **void QDrag::setHotSpot(const QPoint & hotspot )**

        Sets the position of the hot spot relative to the top-left corner of the pixmap used to the point specified by **hotspot**.

        **Note:** on X11, the pixmap may not be able to keep up with the mouse movements if the hot spot causes the pixmap to be displayed directly under the cursor.

        **See also** **hotSpot** ().
        """
        ...

    def setMimeData(self, data: PySide2.QtCore.QMimeData) -> None:
        """
        https://doc.qt.io/qt-5/qdrag.html#setMimeData

        **void QDrag::setMimeData(QMimeData * data )**

        Sets the data to be sent to the given MIME **data**. Ownership of the data is transferred to the **QDrag**  object.

        **See also** **mimeData** ().
        """
        ...

    def setPixmap(self, arg__1: PySide2.QtGui.QPixmap) -> None:
        """
        https://doc.qt.io/qt-5/qdrag.html#setPixmap

        **void QDrag::setPixmap(const QPixmap & pixmap )**

        Sets **pixmap** as the pixmap used to represent the data in a drag and drop operation. You can only set a pixmap before the drag is started.

        **See also** **pixmap** ().
        """
        ...

    def source(self) -> PySide2.QtCore.QObject:
        """
        https://doc.qt.io/qt-5/qdrag.html#source

        **QObject *QDrag::source() const**

        Returns the source of the drag object. This is the widget where the drag and drop operation originated.
        """
        ...

    def start(
        self, supportedActions: PySide2.QtCore.Qt.DropActions = ...
    ) -> PySide2.QtCore.Qt.DropAction:
        ...

    def supportedActions(self) -> PySide2.QtCore.Qt.DropActions:
        """
        https://doc.qt.io/qt-5/qdrag.html#supportedActions

        **Qt::DropActions QDrag::supportedActions() const**

        Returns the set of possible drop actions for this drag operation.

        **See also** **exec** () and **defaultAction** ().
        """
        ...

    def target(self) -> PySide2.QtCore.QObject:
        """
        https://doc.qt.io/qt-5/qdrag.html#target

        **QObject *QDrag::target() const**

        Returns the target of the drag and drop operation. This is the widget where the drag object was dropped.
        """
        ...

    @property
    def actionChanged(self) -> PySide2.QtCore.SignalInstance:
        """
        https://doc.qt.io/qt-5/qdrag.html#actionChanged

        **[signal] void QDrag::actionChanged(Qt::DropAction action )**

        This signal is emitted when the **action** associated with the drag changes.

        **See also** **targetChanged** ().
        """
        ...

    @property
    def targetChanged(self) -> PySide2.QtCore.SignalInstance:
        """
        https://doc.qt.io/qt-5/qdrag.html#targetChanged

        **[signal] void QDrag::targetChanged(QObject * newTarget )**

        This signal is emitted when the target of the drag and drop operation changes, with **newTarget** the new target.

        **See also** **target** () and **actionChanged** ().
        """
        ...
