[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "searchalg"
authors = [{name = "Hatchi Kiqo", email = "hatchikiqo@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.7"
dependencies = [
    "loguru >= 0.5.3"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]