[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bean_mortgage"
authors = [{name = "Gerry Agbobada", email = "pypi@gagbo.net"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "python-dateutil >= 2.8"
]

[project.scripts]
bean-mortgage = "bean_mortgage:main"
