[tool.poetry]
name = "zotero2readwise"
version = "0.1.0"
description = ""
authors = ["ealizadeh <alizadeh.essi@gmail.com>"]
license = "MIT"

[tool.semantic_release]
version_variable = [
    "zotero2readwise/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "release"
upload_to_repository = true
upload_to_release = true
build_command = "pip install poetry && poetry build"

[tool.poetry.dependencies]
python = "^3.8"
Pyzotero = "^1.4.26"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
ipython = "^7.30.1"
pre-commit = "^2.16.0"
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
