[tool.poetry]
name = "ns-poet"
version = "0.6.0"
description = "Autogenerate Poetry package manifests in a monorepo"
authors = ["Jonathan Drake <jdrake@narrativescience.com>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/NarrativeScience/ns-poet"
repository = "https://github.com/NarrativeScience/ns-poet"

[tool.poetry.dependencies]
python = "^3.6.5"
click = ">=7.0"
cookiecutter = "^1.7.3"
setuptools = "^58.5.3"
astor = "^0.8.1"
networkx = "<2.6"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.10.1"
pytest = "^6.2.2"
black = {version = "^21.9b0", allow-prereleases = true}
cruft = "^2.9.0"

[tool.cruft]
skip = ["pyproject.toml", "ns_poet", "tests", "README.md", ".circleci/config.yml"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nspoet = "ns_poet.cli:cli"
