
name: jupyterlab_server_documentation
channels:
  - conda-forge
dependencies:
- python=3.8
- sphinx<4.0
- sphinx-copybutton
- pip
- myst-parser
- pip:
  - autodoc-traits
  - pydata_sphinx_theme
  - sphinxcontrib-openapi
  - numpydoc
