[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyseto"
version = "1.6.2"
description = "A Python implementation of PASETO/PASERK."
authors = ["Ajitomi Daisuke <dajiaji@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dajiaji/pyseto"

include = [
  "CHANGES.rst",
  "docs",
  "poetry.lock",
  "tests",
  "tox.ini",
]

exclude = [
  "docs/_build",
]

[tool.poetry.dependencies]
python = "^3.6.2"
cryptography = "^36.0.0"
pycryptodomex = "^3.12.0"
passlib = {extras = ["argon2"], version = "^1.7.4"}
iso8601 = "^1.0.2"
Sphinx = {version = "^4.3.1", extras = ["docs"]}
sphinx-autodoc-typehints = {version = "^1.12.0", extras = ["docs"]}
sphinx-rtd-theme = {version = "^1.0.0", extras = ["docs"]}

[tool.poetry.extras]
docs = [
  "Sphinx",
  "sphinx-rtd-theme",
  "sphinx-autodoc-typehints",
]

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^3.0.0"
tox = "^3.24.4"
pre-commit = "^2.15.0"
mypy = "^0.930"
freezegun = "^1.1.0"

[tool.mypy]
ignore_missing_imports = true
