[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

dependencies = [
    "build==0.7.0",
    "certifi==2021.10.8",
    "charset-normalizer==2.0.10",
    "idna==3.3",
    "packaging==21.3",
    "pep517==0.12.0",
    "pyparsing==3.0.6",
    "requests==2.27.0",
    "requests-toolbelt==0.9.1",
    "tomli==2.0.0",
    "urllib3==1.26.7"
]