[tool.pytest.ini_options]
addopts = "--cov=agoradesk_py"
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.poetry]
name = "agoradesk_py"
version = "0.2.0"
description = "Python Interface for Agoradesk.com and LocalMonero.co API"
authors = ["marvin8 <marvin8@tuta.io>"]
license = "AGPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Intended Audience :: Developers",
    "Topic :: Office/Business :: Financial"
]

[tool.poetry.dependencies]
python = "^3.7"
arrow = "^1.2.1"
httpx = "^0.21.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
pytest-cov = "^3.0.0"
pylint = "^2.12.2"
pytest-testmon = "^1.2.2"
pytest = "^6.2.5"
black = "^21.12b0"
mypy = "^0.931"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
