"""
PySide2 stub files generated by **IceSpringPySideStubs**

Home page: https://github.com/baijifeilong/IceSpringPySideStubs

Generated by BaiJiFeiLong@gmail.com

Licence: GPL-3
"""
from ._QCameraViewfinder import QCameraViewfinder as QCameraViewfinder
from ._QGraphicsVideoItem import QGraphicsVideoItem as QGraphicsVideoItem
from ._QVideoWidget import QVideoWidget as QVideoWidget
from ._QVideoWidgetControl import QVideoWidgetControl as QVideoWidgetControl
