[tool.poetry]
name = "pocketchemist"
version = "0.1.0"
description = "Software for the analysis of spectra and molecules"
authors = ["J Lorieau"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.0"
scipy = "^1.7.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
