[tool.poetry]
name = "skit-fixdf"
version = "0.1.0"
description = "A library to format datasets so that you don't have to."
authors = ["ltbringer <amresh.venugopal@gmail.com>"]
license = "GPL-3"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
