[project]
name = "flaggart"
version = "0.4.1"
description = "Package for retrieving, creating, and performing operations on flags"
authors = ["AlDacMac <alasdairmacgdev@gmail.com>"]
license = "MIT"
readme = "./README.md"

[tool.poetry]
name = "flaggart"
version = "0.4.1"
description = "Package for retrieving, creating, and performing operations on flags"
authors = ["AlDacMac <alasdairmacgdev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
wikipedia = "^1.4.0"
Pillow = "^8.3.2"
Wand = "^0.6.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
Sphinx = "^4.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
