[tool.poetry]
name = "aipkgs-core"
version = "0.0.3"
description = ""
authors = ["Alexy <alexy.ib@outlook.com>"]
# New attributes
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/aipy/common"
repository = "https://gitlab.com/aipy/common"
keywords = ["ai"]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
pendulum = "^2.1.2"
email-validator = "^1.1.3"
emoji = "^1.6.1"
phonenumbers = "^8.12.40"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
