mqtt:
  host: mqtt.hass
  username: mqtt
  password: pass
  topic_prefix: boneiohome
  ha_discovery:
    enabled: yes

i2c:
  id: myb
  sda: P9_18
  scl: P9_17

oled:

mcp23017:
  - id: mcp1
    address: 0x20

gpio_input:
  - id: "one"
    pin: P8_12
  - id: "two"
    pin: P8_7
    actions:
      single:
        action: output
        pin: myoutput

output: !include output.yaml


##OUTPUT.YAML
- id: myoutput
  kind: mcp
  mcp_id: mcp1
  pin: 0
  ha_type: light
