from typing import Any

from .packettypes import PacketTypes as PacketTypes

class ReasonCodes:
    packetType: Any
    names: Any
    value: Any
    def __init__(self, packetType, aName: str = ..., identifier: int = ...) -> None: ...
    def __getName__(self, packetType, identifier): ...
    def getId(self, name): ...
    def set(self, name) -> None: ...
    def unpack(self, buffer): ...
    def getName(self): ...
    def __eq__(self, other): ...
    def json(self): ...
    def pack(self): ...
