[tool.poetry]
name = "wordle-trainer"
version = "0.0.1"
description = "A cli wordle clone that gives you hints as you play."
authors = ["Matthew Anderson <matt@manderscience.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/maxb2/wordle-trainer"
repository = "https://github.com/maxb2/wordle-trainer"
include = ['poetry.lock']

[tool.poetry.scripts]
wordle-trainer = 'wordle_trainer.wordle:app'

[tool.poetry.dependencies]
python = "^3.9.6"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
black = "^21.4b1"
bump2version = "^1.0.0"
pylint = "^2.4.0"
pytest = "^6.0.0"
pytest-cov = "^3.0.0"
pytest-runner = "^5.2.0"
pytest-watch = "^4.2.0"
twine = "^3.0.0"
wheel = "^0.34.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
