[tool.poetry]
name = "cubexplain"
version = "0.1.11"
description = ""
authors = []

[tool.poetry.scripts]
cubexplain = "cubexplain.commande_line:main"

[tool.poetry.dependencies]
atoti = {extras = ["sql"], version = "*"}
# Poetry deletes this package when the --no-dev flag is enabled because it is a dependency of requests, however it is needed for package installation.
certifi = "*"
pandas = "*"
python = "^3.9"
watchdog = "^2.1.6"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
black = "*"
docker = "*"
isort = "*"
mypy = "*"
pandas-stubs = "*"
pylint = "*"
pytest = "*"
requests = "*"
types-requests = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_calls = false

[[tool.mypy.overrides]]
module = ["docker"]
ignore_missing_imports = true

[tool.pylint."messages control"]
ignore = [".venv"]
disable = [
  "line-too-long", # Handled by Black.
  # Do not force docstrings.
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "singleton-comparison", # So that code such as `m["Boolean"] == True` can be used.
  "useless-import-alias", # Goes against https://www.python.org/dev/peps/pep-0484/#stub-files.
]
good-names = ["at", "h", "l", "m"]
