"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

PyPI(PySide6): https://pypi.org/project/IceSpringPySideStubs-PySide6

PyPI(PyQt5): https://pypi.org/project/IceSpringPySideStubs-PyQt5

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
"""
This file contains the exact signatures for all functions in module
PySide2.QtQml, except for defaults which are replaced by "...".
"""
import PySide2
import typing
import PySide2.QtCore
import PySide2.QtNetwork
import PySide2.QtQml

bytes = str


class QtQml(object):
    """
    https://doc.qt.io/qt-5/qtqml.html

    **Detailed Description**
    """

    @staticmethod
    def qmlAttachedPropertiesObject(
        arg__2: PySide2.QtCore.QObject, arg__3: PySide2.QtCore.QMetaObject, create: bool
    ) -> typing.Tuple:
        ...

    @staticmethod
    def qmlAttachedPropertiesObjectById(
        arg__1: int, arg__2: PySide2.QtCore.QObject, create: bool = ...
    ) -> PySide2.QtCore.QObject:
        ...

    @staticmethod
    def qmlContext(arg__1: PySide2.QtCore.QObject) -> PySide2.QtQml.QQmlContext:
        ...

    @staticmethod
    def qmlEngine(arg__1: PySide2.QtCore.QObject) -> PySide2.QtQml.QQmlEngine:
        ...

    @staticmethod
    def qmlExecuteDeferred(arg__1: PySide2.QtCore.QObject) -> None:
        ...
