[tool.poetry]
name = "coshed-flask"
version = "0.14.0"
description = "flask helper for lazy developer(s)"
authors = ["doubleO8 <wb008@hdm-stuttgart.de>"]

[tool.poetry.dependencies]
python = "^3.6.2"
Flask = "^2.0.2"
Flask-Compress = "^1.10.1"
Flask-Cors = "^3.0.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.5b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
