[tool.mypy]
python_version=3.7
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.pycln]
all = true

[tool.vulture]
exclude = []
ignore_decorators = []
ignore_names = []
make_whitelist = true
min_confidence = 80
paths = ['.']
sort_by_size = true
verbose = false

[tool.poetry]
name = "Playlist2Podcast"
version = "0.2.3"
description = "Creates podcast feed from playlist URL"
readme = "README.md"
repository = "https://codeberg.org/PyYtTools/Playlist2Podcasts"
authors = ["marvin8 <marvin8@tuta.io>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.1"
httpx = "~=0.19"
feedgen = "^0.9.0"
youtube_dl = "^2021.12.17"
rich = "^10.16.1"
Pillow = "^9.0.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
pylint = "^2.12.2"
flake8 = "^4.0.1"
mypy = "^0.930"
vulture = "^2.3"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
