[tool.poetry]
name = "radiocc"
version = "0.6.13"
description = "Radio occultations"
license = "Apache-2.0"
authors = ["Ananya Krishnan <ananyakrishnaniiserk@gmail.com>", "Greg Henry <gregoire.henry@oma.be>"]
readme = "README.md"
repository = "https://gitlab-as.oma.be/gregoireh/radiocc"
keywords = ["radio", "occultation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Telecommunications Industry",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Programming Language :: Python :: 3.9",
    "Environment :: Console",
    "Framework :: Matplotlib",
    "Framework :: Pytest",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: POSIX :: Linux",
    "Natural Language :: English",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pudb = "^2021.1"
click = "^8.0.1"
envtoml = "^0.1.2"
dotmap = "^1.3.24"
PyYAML = "^5.4.1"
"ruamel.yaml" = "^0.17.16"
colored = "^1.4.2"
numpy = "^1.21.2"
nptyping = "^1.4.3"
scipy = "^1.7.1"
spiceypy = "^4.0.2"
matplotlib = "^3.4.3"
pandas = "^1.3.2"
arrow = "^1.1.1"
bs4 = "^0.0.1"
urlpath = "^1.1.7"
tqdm = "^4.62.3"
requests = "^2.26.0"
PyGObject = "^3.42.0"
pycairo = "^1.20.1"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
flake8-bugbear = "^21.4.3"
isort = "^5.9.3"
mypy = "^0.910"
pre-commit = "^2.15.0"
pytest = "^6.2.5"
pytest-sugar = "^0.9.4"
pytest-cov = "^2.12.1"
python-language-server = "^0.26"
neovim = "^0.3.1"
pynvim = "^0.4.3"
twine = "^3.4.2"
flake8 = "^3.9.2"
types-requests = "^2.25.9"
types-click = "^7.1.5"
types-PyYAML = "^5.4.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
radiocc = "radiocc.cli:main"

[tool.pytest]
testpaths = "tests"

[tool.mypy]
files = ["radiocc", "tests"]
exclude = "radiocc/old"
follow_imports = "silent"
strict = true
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true

[tool.black]
line_length = 88
exclude = "radiocc/old"

[tool.isort]
profile = "black"
skip = "radiocc/old"
