[tool.poetry]
name = "paho-mqtt-stubs"
version = "0.1.0"
description = "Type stubs for the paho MQTT client library"
authors = ["Dániel Hagyárossy <d.hagyarossy@sapstar.eu>"]
license = "MIT"
repository = "https://github.com/atraides/paho-mqtt-stubs"
packages = [
    { include = "paho-stubs" },
]
classifiers = [
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7"
paho-mqtt = "^1.6.1"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10.1"
flake8 = "^4.0.1"

[tool.isort]
profile = "black"
known_first_party = [
    "paho",
]
combine_as_imports = true
float_to_top = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
