[tool.poetry]
name = "seckerwiki"
version = "2.0.12"
description = "A collection of scripts used to manage my personal Foam workspace"
authors = ["Benjamin Secker <benjamin.secker@gmail.com>"]
repository = "https://github.com/bsecker/wiki/"
documentation = "https://github.com/bsecker/wiki/blob/master/README.md"
readme = "README.md"

[tool.poetry.scripts]
wiki = "seckerwiki.wiki:main"

[tool.poetry.dependencies]
python = "^3.6"
PyInquirer = "^1.0.3"
PyYAML = "^5.4.1"
pdf2image = "^1.16.0"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
