VERSION_YEAR = 2022
VERSION_MONTH = int('01')
VERSION_DAY = int('02')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('45')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202201021145
version_date = '2022/01/02 11:45'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
