[tool.poetry]
name = "sleepyr"
version = "0.0.1"
description = "Python Sleeper API client"
authors = ["Craig Martek <craigmartek@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
yapf = "^0.32.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
