[tool.poetry]
name = "kbackground"
version = "0.1.4"
description = ""
authors = ["Christina Hedges <christina.l.hedges@nasa.gov>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = "^1.21.4"
scipy = "^1.7.3"
patsy = "^0.5.2"
astropy = "^4.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = "^21.12b0"
isort = "^5.10.1"
mkdocs = "^1.2.3"
mkdocs-material = "^8.1.0"
mkdocstrings = "^0.16.2"
jupyterlab = "^3.2.5"
matplotlib = "^3.5.0"
lightkurve = "^2.0.11"
mkdocs-jupyter = "^0.19.0"
pytkdocs = {version = "0.12", extras = ["numpy-style"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
