[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project]
dynamic = []
requires-python = ">=3.6"
dependencies = []
description = "A markdown parser with high extensibility."
name = "marko"
readme = "README.md"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Operating System :: OS Independent", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10",]
version = "1.2.0"
[[project.authors]]
name = "Frost Ming"
email = "mianghong@gmail.com"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/frostming/marko"
Documentation = "https://marko-py.readthedocs.io"

[project.optional-dependencies]
toc = [ "python-slugify",]
codehilite = [ "pygments",]
benchmark = [ "commonmark~=0.9", "markdown~=3.3", "markdown-it-py~=2.0", "mistune~=2.0", "mistletoe~=0.7",]

[project.scripts]
marko = "marko.cli:main"

[tool.pdm.version]
from = "marko/__init__.py"

[tool.pdm.dev-dependencies]
dev = [ "pytest<7.0.0,>=6.1.2", "pytest-cov<3.0.0,>=2.10.1", "mypy", "nox~=2020.12",]
