[tool.poetry]
name = "easy-user-input"
version = "1.2.1"
description = "Misc python3 methods for collecting input from users"
authors = ["generic-user1 <89677116+generic-user1@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
