[tool.poetry]
name = "shawl"
version = "0.2.0"
description = ""
authors = ["JackZ <1144732003@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "pyarmor>=7.2.0", "opencv_python", "pillow"]
build-backend = "pyarmor.build_meta"
