# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['shawl',
 'shawl.pyminicap',
 'shawl.pyminicap.pytransform',
 'shawl.pyminitouch',
 'shawl.pyminitouch.pytransform',
 'shawl.pytransform']

package_data = \
{'': ['*'],
 'shawl': ['Lib/minicap-prebuilt/arm64-v8a/bin/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-21/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-22/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-23/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-24/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-25/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-26/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-27/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-28/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-29/*',
           'Lib/minicap-prebuilt/arm64-v8a/lib/android-30/*',
           'Lib/minicap-prebuilt/armeabi-v7a/bin/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-10/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-14/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-15/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-16/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-17/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-18/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-19/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-21/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-22/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-23/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-24/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-25/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-26/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-27/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-28/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-29/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-30/*',
           'Lib/minicap-prebuilt/armeabi-v7a/lib/android-9/*',
           'Lib/minicap-prebuilt/noarch/*',
           'Lib/minicap-prebuilt/x86/bin/*',
           'Lib/minicap-prebuilt/x86/lib/android-14/*',
           'Lib/minicap-prebuilt/x86/lib/android-15/*',
           'Lib/minicap-prebuilt/x86/lib/android-16/*',
           'Lib/minicap-prebuilt/x86/lib/android-17/*',
           'Lib/minicap-prebuilt/x86/lib/android-18/*',
           'Lib/minicap-prebuilt/x86/lib/android-19/*',
           'Lib/minicap-prebuilt/x86/lib/android-21/*',
           'Lib/minicap-prebuilt/x86/lib/android-22/*',
           'Lib/minicap-prebuilt/x86/lib/android-23/*',
           'Lib/minicap-prebuilt/x86/lib/android-24/*',
           'Lib/minicap-prebuilt/x86/lib/android-25/*',
           'Lib/minicap-prebuilt/x86/lib/android-26/*',
           'Lib/minicap-prebuilt/x86/lib/android-27/*',
           'Lib/minicap-prebuilt/x86/lib/android-28/*',
           'Lib/minicap-prebuilt/x86/lib/android-29/*',
           'Lib/minicap-prebuilt/x86/lib/android-30/*',
           'Lib/minicap-prebuilt/x86_64/bin/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-21/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-22/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-23/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-24/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-25/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-26/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-27/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-28/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-29/*',
           'Lib/minicap-prebuilt/x86_64/lib/android-30/*',
           'Lib/minitouch-prebuilt/arm64-v8a/bin/*',
           'Lib/minitouch-prebuilt/armeabi-v7a/bin/*',
           'Lib/minitouch-prebuilt/x86/bin/*',
           'Lib/minitouch-prebuilt/x86_64/bin/*']}

setup_kwargs = {
    'name': 'shawl',
    'version': '0.2.0',
    'description': '',
    'long_description': None,
    'author': 'JackZ',
    'author_email': '1144732003@qq.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)
