[tool.poetry]
name = "ntfy-bark"
version = "0.1.0"
description = "Bark backend for ntfy"
authors = ["Cologler <skyoflw@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.0"

[tool.poetry.dev-dependencies]
ntfy = "^2.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
