[tool.poetry]
name = "zit"
version = "0.0.1-alpha.1"
description = "CLI for Zityspace API"
authors = ["Zityspace <team@zityspace.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
ipython = "^7.31.0"
ipdb = "^0.13.9"
click = "^8.0.3"

[tool.poetry.scripts]
zit = "zit.main:start"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
