[tool.poetry]
name = "ecceran"
version = "0.1.1"
description = "Simple ECC encrypt decrypt"
authors = ["hfrada <madefrada@gmail.com>"]
readme = "README.md"
packages = [
    { include = "ecceran" },
]

[tool.poetry.dependencies]
python = "^3.9"
pycryptodome = "3.12.0"
coincurve = "16.0.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
ecceran = "ecceran.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
