[tool.poetry]
name = "aliby-agora"
version = "0.1.1"
description = "A gathering of shared utilities for the Swain Lab image processing pipeline."
authors = ["Alán Muñoz <amuoz@ed.ac.uk>", "Diane Adjavon <diane.adjavon@ed.ac.uk>"]
license = "GPL-3.0-or-later"
packages = [
    { include = "agora" },
]

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
Sphinx = "^4.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
