[tool.poetry]
name = "futurecandy"
version = "1.2.1"
description = "Project initialization utility for Linux."
authors = ["perpetualCreations <tchen0584@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://dreamerslegacy.xyz/"
repository = "https://dreamerslegacy.xyz/git/perpetualCreations/futurecandy"

[tool.poetry.dependencies]
python = "^3.9"
enquiries = "^0.1.0"
prompt-toolkit = "^3.0.20"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pydocstyle = "^6.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
