name: Test ROSSpy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Pip, pytest, rosspy
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install rosspy
      - name: Run tests
        run: pytest /home/runner/work/ROSSpy/ROSSpy/rosspy/test/test_core.py