[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bandsaw"
authors = [
    {name = "Christoph Emonds", email = "chris+git@kant.ai"},
]
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.6"
dynamic = ['version', 'description']
keywords = [
    "machine learning",
    "tasks",
    "computation",
    "graph",
    "distributed",
]
dependencies = [
]

[project.urls]
Documentation = "https://docs.kant.ai/bandsaw/latest/"
Source = "https://gitlab.com/kantai/bandsaw/"

[project.optional-dependencies]
test = [
    "tox",
]
docs = [
    "tox",
]
release = [
    "flit",
]
multimeter = [
    "multimeter",
]
