[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true

[tool.pylint.MASTER]
py-version = "3.8"
ignore = [
    "tests",
]
jobs = 2

[tool.pylint.BASIC]
good-names = [
    "_",
    "kw",
    "i",
    "j",
    "k",
    "v",
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
