[tool.poetry]
name = "aliby-extraction"
version = "0.1.1"
description = ""
authors = ["Alán Muñoz <amuoz@ed.ac.uk>"]
license = "GPL-3.0-or-later"
packages = [
    { include = "extraction" },
]

[tool.poetry.dependencies]
python = "^3.7"
numpy = ">=1.17.3"
scipy = ">=1.4.1"
scikit-image = ">=0.19.1"
more-itertools = "^8.12.0"
py-find-1st = "^1.1.5"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
