# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude_types: [svg]
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]
-   repo: https://github.com/ckear1989/jinjalint
    rev: dependency_version_update
    hooks:
    - id: jinjalint
      types: [html]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.3.0
    hooks:
    - id: eslint
-   repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: ["--max-line-length", "100"]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
    -   id: pylint_badge
        name: pylint-badge
        entry:
            scripts/pylint-badge.sh
        language: system
        types: [python]
    -   id: pytest
        name: pytest
        entry: pytest --codeblocks
        language: system
        types: [python]
        pass_filenames: false
