"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

PyPI(PySide6): https://pypi.org/project/IceSpringPySideStubs-PySide6

Generated by BaiJiFeiLong@gmail.com

Licence: GPLv3
"""
from enum import Enum
from typing import overload
import PySide6.QtCore
import PySide6.QtBluetooth

bytes = str


class QBluetooth(object):
    """
    https://doc.qt.io/qt-6/qbluetooth.html

    **Detailed Description**
    """

    class AttAccessConstraint(Enum):
        AttAuthorizationRequired: QBluetooth.AttAccessConstraint = ...
        AttAuthenticationRequired: QBluetooth.AttAccessConstraint = ...
        AttEncryptionRequired: QBluetooth.AttAccessConstraint = ...

    class AttAccessConstraints(object):
        ...

    class Security(Enum):
        NoSecurity: QBluetooth.Security = ...
        Authorization: QBluetooth.Security = ...
        Authentication: QBluetooth.Security = ...
        Encryption: QBluetooth.Security = ...
        Secure: QBluetooth.Security = ...

    class SecurityFlags(object):
        ...

    @overload
    @staticmethod
    def qt_getEnumMetaObject(
        arg__1: PySide6.QtBluetooth.QBluetooth.AttAccessConstraint,
    ) -> PySide6.QtCore.QMetaObject:
        ...

    @overload
    @staticmethod
    def qt_getEnumMetaObject(
        arg__1: PySide6.QtBluetooth.QBluetooth.Security,
    ) -> PySide6.QtCore.QMetaObject:
        ...

    @overload
    @staticmethod
    def qt_getEnumName(
        arg__1: PySide6.QtBluetooth.QBluetooth.AttAccessConstraint,
    ) -> bytes:
        ...

    @overload
    @staticmethod
    def qt_getEnumName(arg__1: PySide6.QtBluetooth.QBluetooth.Security) -> bytes:
        ...
