[tool.poetry]
name = "mac_format"
version = "0.2.0"
description = ""
authors = ["Lucas <lucasbmello96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pygubu-designer = "^0.19"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
