sudo: false
dist: xenial
language: python
cache: pip
git:
  lfs_skip_smudge: true
matrix:
  include:
  - python: '3.7'
    os: linux
before_install:
- git config lfs.fetchexclude "pymontecarlo_casino2/casino2"
- git lfs pull
install:
- pip install --upgrade git+https://github.com/pymontecarlo/pymontecarlo.git
- pip install --upgrade pip codecov
- pip install --upgrade -e .[dev,gui]
script:
- pytest
after_success:
- codecov
notifications:
  email: false