[tool.poetry]
name = "token_api"
version = "1.0.0"
description = "Make a Token encryption"
authors = ["OwoNicoo"]
license = "GNU-V3"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
