[project]
name = "tox-pdm"
description = "A plugin for tox that utilizes PDM as the package manager and installer"
dependencies = [ "tox>=3.18.0", "toml>=0.10",]
requires-python = ">=3.7"
dynamic = []
readme = "README.md"
keywords = [ "tox", "testing",]
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers",]
version = "0.3.2"
[[project.authors]]
name = "Frost Ming"
email = "mianghong@gmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/pdm-project/tox-pdm"
Repository = "https://github.com/pdm-project/tox-pdm"

[project.optional-dependencies]
test = [ "pytest>=6.2", "coverage>=5.5",]
lint = [ "flake8>=3.8", "black>=20.8b1",]

[tool.black]
line-length = 88
exclude = "/(\n    \\.eggs\n  | \\.git\n  | \\.hg\n  | \\.mypy_cache\n  | \\.tox\n  | \\.venv\n  | _build\n  | buck-out\n  | build\n  | dist\n)/\n"

[tool.isort]
profile = "black"
atomic = true
skip_glob = [ "*/setup.py",]
filter_files = true

[project.entry-points.tox]
pdm = "tox_pdm.plugin"

[tool.pdm.version]
use_scm = true

[tool.pytest.ini_options]
filterwarnings = [ "ignore::DeprecationWarning",]
