
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-06T04:31:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "596897ab7ca301d8776eebecea53b7c9cd483006",
 "version": "1.16.0.post.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
