[tool.poetry]
name = "sdss-bossICC"
version = "6.0.1"
description = "The BOSS Instrument Control Computer for APO."
authors = ["Craig Loomis"]
maintainers = ["José Sánchez-Gallego <gallegoj@uw.edu>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/sdss/bossICC"
repository = "https://github.com/sdss/bossICC"
keywords = ["astronomy", "software"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [
    { include = "bossICC", from = "python" }
]
include = ["python/bossICC/etc/*"]

[tool.poetry.dependencies]
python = "^3.9"
sdss-actorcore = "^5.0.4"
sdsstools = ">=0.4.13"
astropy = "^4.3.1"
numpy = "^1.21.1"
Twisted = "^21.7.0"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
ipython = ">=8.0.0rc1"
invoke = ">=1.3.0"
flake8 = ">=3.7.9"
doc8 = ">=0.8.0"
pytest = ">=5.2.2"
pytest-cov = ">=2.8.1"
pytest-sugar = ">=0.9.2"
isort = ">=4.3.21"
codecov = ">=2.0.15"
coverage = {version = ">=5.0", extras = ["toml"]}
ipdb = ">=0.12.3"
toml = ">=0.10.0"
black = {version = "^21.7b0", allow-prereleases = true}

[tool.poetry.scripts]
bossICC = 'bossICC.BossICC:run_actor'

[tool.black]
line-length = 88
target-version = ['py39']
fast = true

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "TYPING", "THIRDPARTY", "SDSS", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
known_first_party = "bossICC"
known_typing = ["typing"]
known_sdss = ["sdsstools", "actorcore", "opscore"]
lines_after_imports = 2

[tool.pytest.ini_options]
addopts = "--cov bossICC --cov-report xml --cov-report html --cov-report term"

[tool.coverage.report]
exclude_lines = []

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=49.6.0"]
build-backend = "poetry.core.masonry.api"
