[tool.poetry]
name = "aliby-extraction"
version = "0.1.2"
description = ""
authors = ["Alán Muñoz <amuoz@ed.ac.uk>"]
license = "GPL-3.0-or-later"
packages = [
    { include = "extraction" },
]

[tool.poetry.dependencies]
python = "^3.7.1,<3.11"
numpy = ">=1.17.3"
scipy = ">=1.4.1"
pandas = "^1.3.5"
scikit-learn = "0.22.2.post1"
scikit-image = ">=0.19.1"
h5py = "2.10"
tqdm = "^4.62.3"
more-itertools = "^8.12.0"
py-find-1st = "^1.1.5"
aliby-agora = "*"

[tool.poetry.dev-dependencies]
data-science-types = "^0.2.23"
black = "^21.12b0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"
matplotlib = "^3.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
