[tool.poetry]
name = "contestfs"
version = "0.0.8"
description = "continuously test file system changes, and run a command."
license = "MIT"
authors = ["Jeong-Min Lee"]
packages = [
    { include = "contestfs.py"}
]
readme = "README.md"

[tool.poetry.scripts]
contestfs = "contestfs:main"

[tool.poetry.dependencies]
python = "^3.7"
watchdog = "^2.0.0"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-import-order = "^0.18.1"
types-colorama = "^0.4.6"
mypy = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
