[build-meta]
requires = ["setuptools>=42.0", "wheel", "twine"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
    testpaths = ["tests", ]

[tool.mypy]
strict = true
warn_unreachable = true
