[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "999"

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore=noxfile.py -n=auto -v --cov=pydaymet --cov-report xml --durations=5"
doctest_optionflags = 'NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL NUMBER'
testpaths = [
    "tests",
    "pydaymet",
]
filterwarnings = [
    "ignore:.*this is an initial implementation.*",
]

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = "pydaymet"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100

[tool.mypy]
strict = true
