[tool.poetry]
name = "td-connect"
version = "0.1.0"
description = "Authentication manager for TD Ameritrade REST APIs."
authors = ["Dan Kelleher <dan@danklabs.org>"]

[tool.poetry.dependencies]
python = "^3.9"
python-dateutil = "^2.8.2"
requests = "^2.26.0"
websockets = "^10.1"
logzero = "^1.7.0"
aiohttp = "^3.8.1"
fsspec = {extras = ["gcs"], version = "^2021.11.1"}

[tool.poetry.dev-dependencies]
pytest = {version = "^5.2", optional = true}
pytest-asyncio = {version = "^0.16.0", optional = true}
pylama = {extras = ["all"], version = "^8.3.6", optional = true}
black = {version="^21.12b0", optional = true}
jupyter = {version="^1.0.0", optional = true}
python-dotenv = {version="^0.19.2", optional = true}

[tool.poetry.extras]
examples = ["python-dotenv"]
test = ["pytest", "pytest-asyncio"]
lint = ["pylama", "black"]
dev = ["jupyter", "test", "lint", "examples"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
