[tool.poetry]
name = "aipkgs-core"
version = "0.0.2"
description = ""
authors = ["Alexy <alexy.ib@outlook.com>"]
# New attributes
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/aipy/common"
repository = "https://gitlab.com/aipy/common"
keywords = ["ai"]

classifiers = [
    "Environment :: Common libraries",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
