---
background_choice: "kerr_newman"

kerr_newman:
  # Natural (geometrized) units
  mass: 1
  angular_momentum: 0.5
  charge: 0.5

kerr:
  # Natural (geometrized) units
  mass: 1
  angular_momentum: 0.5
  charge: 0  # This must be zero

reissner_nordstrom:
  # Natural (geometrized) units
  mass: 1
  angular_momentum: 0  # This must be zero
  charge: 1

schwarzschild:
  # Natural (geometrized) units
  mass: 1
  angular_momentum: 0  # This must be zero
  charge: 0  # This must be zero

test_particle:
  # Boyer-Lindquist (t,r,theta,phi)
  p0:
    - -0.9764550153430405
    - 0
    - 3.8
    - 3
  q0:
    - 0
    - 20
    - 1.57
    - 0

# It is best to use an absolute path here.
# Accepts Unix or Windows paths, make sure to use double backslashes "\\" for Windows paths.
output_dir: "./output/"

# If you plan to compare your simulations or plot them simultaneously, `num_steps` and `time_step`
# should be the same or their product the same across configuration files. This _must_ be true
# if you plan to plot the geodesics concurrently using the 3D plotting library.
num_steps: 50000
time_step: 0.5 # Seconds
integration_order: 2 # Can be 2 or 4
omega: 1 # Controls how closely the two phase spaces interact. If trajectory varies chaotically over time, make this > 1
