"""
PySide2 stub files generated by **IceSpringPySideStubs**

Home page: https://github.com/baijifeilong/IceSpringPySideStubs

Generated by BaiJiFeiLong@gmail.com

Licence: GPL-3
"""
from ._QAccelerometer import QAccelerometer as QAccelerometer
from ._QAccelerometerFilter import QAccelerometerFilter as QAccelerometerFilter
from ._QAccelerometerReading import QAccelerometerReading as QAccelerometerReading
from ._QAltimeter import QAltimeter as QAltimeter
from ._QAltimeterFilter import QAltimeterFilter as QAltimeterFilter
from ._QAltimeterReading import QAltimeterReading as QAltimeterReading
from ._QAmbientLightFilter import QAmbientLightFilter as QAmbientLightFilter
from ._QAmbientLightReading import QAmbientLightReading as QAmbientLightReading
from ._QAmbientLightSensor import QAmbientLightSensor as QAmbientLightSensor
from ._QAmbientTemperatureFilter import (
    QAmbientTemperatureFilter as QAmbientTemperatureFilter,
)
from ._QAmbientTemperatureReading import (
    QAmbientTemperatureReading as QAmbientTemperatureReading,
)
from ._QAmbientTemperatureSensor import (
    QAmbientTemperatureSensor as QAmbientTemperatureSensor,
)
from ._QCompass import QCompass as QCompass
from ._QCompassFilter import QCompassFilter as QCompassFilter
from ._QCompassReading import QCompassReading as QCompassReading
from ._QDistanceFilter import QDistanceFilter as QDistanceFilter
from ._QDistanceReading import QDistanceReading as QDistanceReading
from ._QDistanceSensor import QDistanceSensor as QDistanceSensor
from ._QGyroscope import QGyroscope as QGyroscope
from ._QGyroscopeFilter import QGyroscopeFilter as QGyroscopeFilter
from ._QGyroscopeReading import QGyroscopeReading as QGyroscopeReading
from ._QHolsterFilter import QHolsterFilter as QHolsterFilter
from ._QHolsterReading import QHolsterReading as QHolsterReading
from ._QHolsterSensor import QHolsterSensor as QHolsterSensor
from ._QHumidityFilter import QHumidityFilter as QHumidityFilter
from ._QHumidityReading import QHumidityReading as QHumidityReading
from ._QHumiditySensor import QHumiditySensor as QHumiditySensor
from ._QIRProximityFilter import QIRProximityFilter as QIRProximityFilter
from ._QIRProximityReading import QIRProximityReading as QIRProximityReading
from ._QIRProximitySensor import QIRProximitySensor as QIRProximitySensor
from ._QLidFilter import QLidFilter as QLidFilter
from ._QLidReading import QLidReading as QLidReading
from ._QLidSensor import QLidSensor as QLidSensor
from ._QLightFilter import QLightFilter as QLightFilter
from ._QLightReading import QLightReading as QLightReading
from ._QLightSensor import QLightSensor as QLightSensor
from ._QMagnetometer import QMagnetometer as QMagnetometer
from ._QMagnetometerFilter import QMagnetometerFilter as QMagnetometerFilter
from ._QMagnetometerReading import QMagnetometerReading as QMagnetometerReading
from ._QOrientationFilter import QOrientationFilter as QOrientationFilter
from ._QOrientationReading import QOrientationReading as QOrientationReading
from ._QOrientationSensor import QOrientationSensor as QOrientationSensor
from ._QPressureFilter import QPressureFilter as QPressureFilter
from ._QPressureReading import QPressureReading as QPressureReading
from ._QPressureSensor import QPressureSensor as QPressureSensor
from ._QProximityFilter import QProximityFilter as QProximityFilter
from ._QProximityReading import QProximityReading as QProximityReading
from ._QProximitySensor import QProximitySensor as QProximitySensor
from ._QRotationFilter import QRotationFilter as QRotationFilter
from ._QRotationReading import QRotationReading as QRotationReading
from ._QRotationSensor import QRotationSensor as QRotationSensor
from ._QSensor import QSensor as QSensor
from ._QSensorBackend import QSensorBackend as QSensorBackend
from ._QSensorBackendFactory import QSensorBackendFactory as QSensorBackendFactory
from ._QSensorChangesInterface import QSensorChangesInterface as QSensorChangesInterface
from ._QSensorFilter import QSensorFilter as QSensorFilter
from ._QSensorGestureManager import QSensorGestureManager as QSensorGestureManager
from ._QSensorGesturePluginInterface import (
    QSensorGesturePluginInterface as QSensorGesturePluginInterface,
)
from ._QSensorGestureRecognizer import (
    QSensorGestureRecognizer as QSensorGestureRecognizer,
)
from ._QSensorManager import QSensorManager as QSensorManager
from ._QSensorPluginInterface import QSensorPluginInterface as QSensorPluginInterface
from ._QSensorReading import QSensorReading as QSensorReading
from ._QTapFilter import QTapFilter as QTapFilter
from ._QTapReading import QTapReading as QTapReading
from ._QTapSensor import QTapSensor as QTapSensor
from ._QTiltFilter import QTiltFilter as QTiltFilter
from ._QTiltReading import QTiltReading as QTiltReading
from ._QTiltSensor import QTiltSensor as QTiltSensor
from ._qoutputrange import qoutputrange as qoutputrange
