"""
PySide2 stub files generated by **IceSpringPySideStubs**

Home page: https://github.com/baijifeilong/IceSpringPySideStubs

Generated by BaiJiFeiLong@gmail.com

Licence: GPL-3
"""
import typing
import PySide2
import PySide2.QtCore
import PySide2.QtSensors

bytes = str


class QProximityFilter(PySide2.QtSensors.QSensorFilter):
    """
    https://doc.qt.io/qt-5/qproximityfilter.html

    **Detailed Description**

    The only difference is that the **filter** () method features a pointer to **QProximityReading**  instead of **QSensorReading** .
    """

    def __init__(self) -> None:
        ...

    @typing.overload
    def filter(self, reading: PySide2.QtSensors.QProximityReading) -> bool:
        """
        https://doc.qt.io/qt-5/qproximityfilter.html#filter

        **[pure virtual] bool QProximityFilter::filter(QProximityReading * reading )**

        Called when **reading** changes. Returns false to prevent the reading from propagating.

        **See also** **QSensorFilter::filter** ().
        """
        ...

    @typing.overload
    def filter(self, reading: PySide2.QtSensors.QSensorReading) -> bool:
        """
        https://doc.qt.io/qt-5/qproximityfilter.html#filter

        **[pure virtual] bool QProximityFilter::filter(QProximityReading * reading )**

        Called when **reading** changes. Returns false to prevent the reading from propagating.

        **See also** **QSensorFilter::filter** ().
        """
        ...
