[tool.poetry]
name = "aliby-baby"
version = "0.1.2"
description = "Birth Annotator for Budding Yeast"
authors = ["Julian Pietsch <jpietsch@ed.ac.uk>", "Alán Muñoz <amuoz@ed.ac.uk>"]
license = "MIT"
packages = [
    { include = "baby" },
]

[tool.poetry.dependencies]
python = "^3.7.1,<3.11"
numpy = "^1.21.4"
tqdm = "^4.62.3"
matplotlib = "^3.5.1"
pandas = "^1.3.5"
scikit-image = "^0.19.1"
scikit-learn = "0.22.2.post1"
Pillow = "^9.0.0"
imageio = "2.8.0"
tensorflow = ">=1.15,<=2.3"
xgboost = "1.4.2"
tune-sklearn = "^0.4.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
Sphinx = "^4.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
