__title__ = 'har2case2'
__description__ = 'fork from https://github.com/HttpRunner/har2case. Convert HAR(HTTP Archive) to YAML/JSON testcases for HttpRunner.'
__url__ = 'https://github.com/alienwow/har2case'
__version__ = '0.3.5'
__author__ = 'Vito'
__author_email__ = 'wuwenhao0327@gmail.com'
__license__ = 'Apache-2.0'
__copyright__ = 'Copyright 2017 debugtalk'