[tool.poetry]
name = "docstats"
version = "0.1.0"
description = "Statistics and other numbers for your sphinx pages"
authors = ["GameDungeon <gamedungeon@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Sphinx = "^4.3.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
mypy = "^0.930"
flake8 = "^4.0.1"
flake8-builtins = "^1.5.3"
flake8-bugbear = "^21.11.29"
flake8-docstrings = "^1.6.0"
flake8-pytest-style = "^1.6.0"
flake8-simplify = "^0.14.2"
flake8-comprehensions = "^3.7.0"
flake8-pie = "^0.15.0"
isort = "^5.10.1"
blacken-docs = "^1.12.0"
black = "^21.12b0"
codespell = "^2.1.0"
furo = "^2022.1.2"
types-docutils = "^0.17.2"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
